<!doctype html>
<html lang="en" data-n-head="%7B%22lang%22:%7B%221%22:%22en%22%7D%7D">
<head>

  <!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-G806HNV51B"></script>
<script>function gtag(){dataLayer.push(arguments)}window.dataLayer=window.dataLayer||[],gtag("js",new Date),gtag("config","G-G806HNV51B")</script>

  <!-- Self-Hosted Chat -->
<script>function getLanguageFromPath(){var t=window.location.pathname;return t.startsWith("/en")?"en":(t.startsWith("/ru")||t.startsWith("/ua"),"ru")}window.chatwootSettings={locale:getLanguageFromPath()},function(t,e){var a="https://chatix1488382.adxfinance",n=t.createElement(e),t=t.getElementsByTagName(e)[0];n.src=a+"/packs/js/sdk.js",n.defer=!0,n.async=!0,t.parentNode.insertBefore(n,t),n.onload=function(){window.chatwootSDK.run({websiteToken:"r4Yb4B2b5vkEP4j76pMaHsUE",baseUrl:a})}}(document,"script")</script>
  <!-- Self-Hosted Chat -->

  <meta data-n-head="1" charset="utf-8"><meta data-n-head="1" name="viewport" content="width=device-width,initial-scale=1"><meta data-n-head="1" data-hid="charset" charset="utf-8"><meta data-n-head="1" data-hid="mobile-web-app-capable" name="mobile-web-app-capable" content="yes"><meta data-n-head="1" data-hid="apple-mobile-web-app-title" name="apple-mobile-web-app-title" content="adxfinance"><meta data-n-head="1" data-hid="description" name="description" content="adxfinance"><meta data-n-head="1" data-hid="theme-color" name="theme-color" content="#121621"><meta data-n-head="1" data-hid="og:type" name="og:type" property="og:type" content="website"><meta data-n-head="1" data-hid="og:title" name="og:title" property="og:title" content="adxfinance"><meta data-n-head="1" data-hid="og:site_name" name="og:site_name" property="og:site_name" content="adxfinance"><meta data-n-head="1" data-hid="og:description" name="og:description" property="og:description" content="adxfinance"><title>adxfinance - adxfinance</title><link data-n-head="1" rel="icon" type="image/x-icon" href="/service/fs/img/favicon/32/favicon.png"><link data-n-head="1" data-hid="shortcut-icon" rel="shortcut icon" href="/_nuxt/icons/icon_16x16.1b5051.png"><link data-n-head="1" data-hid="apple-touch-icon" rel="apple-touch-icon" href="/_nuxt/icons/icon_192x192.1b5051.png" sizes="192x192"><link data-n-head="1" rel="manifest" href="/_nuxt/manifest.5a1f8584.json" data-hid="manifest"><link rel="preload" href="/_nuxt/74a03bc.js" as="script"><link rel="preload" href="/_nuxt/0845d46.js" as="script"><link rel="preload" href="/_nuxt/7c95f9e.js" as="script"><link rel="preload" href="/_nuxt/cef198b.js" as="script">  <link rel="stylesheet" href="/style.css">
</head>
<body>
<div id="__nuxt"><style>#nuxt-loading{background:#fff;visibility:hidden;opacity:0;position:absolute;left:0;right:0;top:0;bottom:0;display:flex;justify-content:center;align-items:center;flex-direction:column;animation:nuxtLoadingIn 10s ease;-webkit-animation:nuxtLoadingIn 10s ease;animation-fill-mode:forwards;overflow:hidden}@keyframes nuxtLoadingIn{0%{visibility:hidden;opacity:0}20%{visibility:visible;opacity:0}100%{visibility:visible;opacity:1}}@-webkit-keyframes nuxtLoadingIn{0%{visibility:hidden;opacity:0}20%{visibility:visible;opacity:0}100%{visibility:visible;opacity:1}}#nuxt-loading>div,#nuxt-loading>div:after{border-radius:50%;width:5rem;height:5rem}#nuxt-loading>div{font-size:10px;position:relative;text-indent:-9999em;border:.5rem solid #f5f5f5;border-left:.5rem solid #006cf0;-webkit-transform:translateZ(0);-ms-transform:translateZ(0);transform:translateZ(0);-webkit-animation:nuxtLoading 1.1s infinite linear;animation:nuxtLoading 1.1s infinite linear}#nuxt-loading.error>div{border-left:.5rem solid #ff4500;animation-duration:5s}@-webkit-keyframes nuxtLoading{0%{-webkit-transform:rotate(0);transform:rotate(0)}100%{-webkit-transform:rotate(360deg);transform:rotate(360deg)}}@keyframes nuxtLoading{0%{-webkit-transform:rotate(0);transform:rotate(0)}100%{-webkit-transform:rotate(360deg);transform:rotate(360deg)}}</style> <script>window.addEventListener("error",function(){var e=document.getElementById("nuxt-loading");e&&(e.className+=" error")})</script> <div id="nuxt-loading" aria-live="polite" role="status"><div>Loading...</div></div> </div><script>window.__NUXT__={config:{_app:{basePath:"/",assetsPath:"/_nuxt/",cdnURL:null}}}</script>

<!-- Yandex.Metrika counter -->
<script type="text/javascript">!function(e,t,c,n,r,a){e.ym=e.ym||function(){(e.ym.a=e.ym.a||[]).push(arguments)},e.ym.l=+new Date;for(var m=0;m<document.scripts.length;m++)if(document.scripts[m].src===n)return;r=t.createElement(c),a=t.getElementsByTagName(c)[0],r.async=1,r.src=n,a.parentNode.insertBefore(r,a)}(window,document,"script","https://mc.yandex.ru/metrika/tag.js"),ym(92883318,"init",{clickmap:!0,trackLinks:!0,accurateTrackBounce:!0,webvisor:!0})</script>
<noscript><div><img src="https://mc.yandex.ru/watch/92883318" style="position:absolute;left:-9999px" alt=""></div></noscript>
<!-- /Yandex.Metrika counter -->

<script src="/_nuxt/74a03bc.js"></script><script src="/_nuxt/0845d46.js"></script><script src="/_nuxt/7c95f9e.js"></script><script src="/_nuxt/cef198b.js"></script></body>
</html>
